### ISSUE TITLE
[BUG] Wrong link in documentation

### ISSUE THREAD

**Issue by probonopd** [luc-github/esp3d.io#14]
**Describe the bug**

http://esp3d.io/esp3d-webui/v3.x/installation/index.html links to 2.x versions of the 
ESP3D-WEBUI.

> The Web UI is represented by one file : index.hml.gz The full package with all languages is available [here](https://github.com/luc-github/ESP3D-WEBUI/blob/2.1/languages/multi/index.html.gz) But it may not fit your available size on flash, so you can select a single language package [here](https://github.com/luc-github/ESP3D-WEBUI/tree/2.1/languages) which is lighter and will fit smallest boards.

If one uploads this, then one gets the error `Otherwise it says "Connection failed! Is your FW correct?".` It is not clear to the user what "connection" failed. The connection between what and what? This cost me hours trying to debug the connection between the 3D printer and the ESP32-CAM when in fact the issue was just caused by a wrong version of the ESP3D-WEBUI. The error message could be clearer.

**To Reproduce**
1. Go to http://esp3d.io/esp3d-webui/v3.x/installation/index.html 
2. Follow the links to index.html.gz

**Expected behavior**

The 3.x documentation links to version 3.x of the index.html.gz

https://github.com/luc-github/ESP3D-WEBUI/blob/3.0/dist/Printer3D/Marlin/index.html.gz

**Comment by luc-github** [comment]
Text modified, site updated  - thank you for pointing this was unmodified copy and past of 2.X doc

>If one uploads this, then one gets the error Otherwise it says "Connection failed! Is your FW correct?"

Error is correct the web ui seems not matching the FW but it is light because I do not want to add a lot of text on something that should not happen

I plan to add a link to troubleshoot to documentation but currently there is not such thing -  I am not good in documentation mostly because most of the time,  even documentation is present people do not read it... orz
